
# from functools import cache
# 
# class _NA: ...
# 
# def file_cache(use_mem_cache=True, threadsafe=True): ...
# def clear_cache(clr_mem=True, clr_file=True): ...
# @file_cache()
# def test_cache(*args, **kwargs): ...
# 
# class NoStr:
#     __slots__ = ...
#     def __init__(self, string: str) -> None: ...
#     def __repr__(self): ...
# 
# class Query:
#     def __init__(self, name, query) -> None: ...
#     def __call__(self, **kwargs): ...
# 
# class LoadSQL:
#     def __init__(self, path) -> None: ...
#     @cache
#     def __repr__(self): ...


from ._quicksql import LoadSQL, NoStr, Query, clear_cache, file_cache, test_cache

"""Parses queries from an sql file, and turns them into callable f-strings. Also a file cache decorator for slow queries and multi-session permanence, supports async functions."""
__version__ = ...
__all__ = ["file_cache", "test_cache", "Query", "LoadSQL", "clear_cache", "NoStr"]
