
from functools import cache

cache_dir = ...
if cache_dir is None:
    cache_dir = ...

class _NA: ...

def file_cache(use_mem_cache=True, threadsafe=True): ...
def clear_cache(clr_mem=True, clr_file=True): ...
@file_cache()
def test_cache(*args, **kwargs): ...

class NoStr:
    __slots__ = ...
    def __init__(self, string: str) -> None: ...
    def __repr__(self): ...

class Query:
    def __init__(self, name, query) -> None: ...
    def __call__(self, **kwargs): ...

class LoadSQL:
    def __init__(self, path) -> None: ...
    @cache
    def __repr__(self): ...
